version: "3.7"

services:
  ################### DATABASES ###################
  docker-mysql_1:
    container_name: mariadb_mysql_database
    image: "mariadb:latest"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=hotelManagement
    ports:
      - 3306:3306
    restart: unless-stopped  


  # docker-mysql_2:
  #   image: "mariadb:latest"
  #   environment:
  #     - MARIADB_ROOT_PASSWORD=root
  #     - MARIADB_DATABASE=hotelManagement
  #   ports:
  #     - 3307:3307

  # docker-postgres:
  #   container_name: postgres_database
  #   image: postgres
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=admin
  #     - POSTGRES_DB=ms_auth_DB

  ################### DISCOVERY SERVER ( eureka) ###################
  discovery_service:
    container_name: serviceregistry
    build: /eureka_server
    ports:
      - "8761:8761"
    hostname: serviceregistry
    image: erueka_service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/

      ################### MICROSERVICES ###################
  ms_customer_review:
    build:
      context: ./ms_customer_review # Set the context to the directory containing your Dockerfile
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - spring.datasource.url=jdbc:mysql://docker-mysql_1:3306/hotelManagement?autoReconnect=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
    ports:
      - "8082:8082"
    image: customer_review
    depends_on:
      - discovery_service
      - docker-mysql_1

  # ms_auth:
  #   container_name: ms_auth
  #   build:
  #     context: ./ms_user_management # Set the context to the directory containing your Dockerfile
  #     dockerfile: Dockerfile
  #   hostname: ms_auth
  #   environment:
  #     - POSTGRES_HOST=docker-postgres
  #     - POSTGRES_PORT=5432
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=admin
  #     - POSTGRES_DATABASE=ms_auth_DB
  #     - EUREKA_HOST=serviceregistry
  #     - EUREKA_PORT=8761
  #     - EUREKA_SEVERPATH=/eureka/apps
  #   ports:
  #     - '7000:7000'
  #   image: ms_auth
  #   depends_on:
  #     - discovery_service
  #     - docker-postgres

  # saff_management_service:
  #   build: /ms_saff_management
  #   environment:
  #     - spring.datasource.url=jdbc:mysql://docker-mysql_2:3307/hotelManagement?autoReconnect=true&useSSL=false
  #     - spring.datasource.username=root
  #     - spring.datasource.password=root
  #     - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
  #     - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
  #   ports:
  #     - "8086:8086"
  #   image: saff_management
  #   depends_on:
  #     - discovery_service
  #     - docker-mysql_2

  ################### GATEWAY SERVER  ###################
  gateway_service:
    container_name: gateway_server
    build: ./gateway-service
    ports:
      - "8089:8089"
    image: gateway_service
    restart: always
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
      - EUREKA_INSTANCE_LEASERENEWALINTERVALINSECONDS=10
      - EUREKA_INSTANCE_LEASEEXPIRATIONDURATIONINSECONDS=30
    
      - spring.cloud.gateway.routes[0].id=ms_customer_review
      - spring.cloud.gateway.routes[0].uri=http://ms_customer_review:8082
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/api/feedback**
    depends_on:
      - discovery_service
      - docker-mysql_1
